<a href="https://colab.research.google.com/github/AndyLightning/SZL-Work/blob/Final-Final/CVS_HW_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Computer Vision Systems Homework**

Hi all!

In the spirit of #StayAtHome I tried to assemble a homework project without leaving the house. So, if this looks a little DIY, that's why. So without further ado:

## **Welcome to Cactusville!**

Cactusville is a small town populated by - you guessed correcty - cacti. Since it is a rapidly developing village, they are considering to use self-driving vehicles in their hometown. Your job as a computer vision maestro is to develop the required detection methods.

## The setting

Cactusville is quite unique in the sense that the entire surface of the town is covered in blue tablecloth. The exact colour and pattern of the cloth may vary slightly.

By-and large there are 3 different objects of interest:

* **Cacti:** These are the inhabitants of the village, so self-driving cars must be able to detect them to avoid hitting a cactus. Cacti have four basic sub-types: ***Happy***, ***Sad***, ***Angry*** and ***Evil***
* **Vehicles:** These are other vechiles you should also avoid colliding with. There are 3 vehicles in Cactusville: An ***SUV***, a ***truck***, and an ***airplane***.
* **Traffic Signs:** There are several signs placed all around the town, often multiple ones on a single stand. There are 55 different traffic sign classes, which are not listed here for the sake of brevity.

## Tasks

The people of Cactusville provided 4 videos for you to develop your algorithms with. Each video consists of several RGB and corresponding depth frames, which are found in the '*rgb*' and '*depth*' subfolders of the video. They are ordered numerically. The depth image is a single-channel, 16-bit image, where the pixel value is the distance of that pixel from the camera in **mm**.

The videos also contain a **calibration.yaml** file, which contains the intrinsic parameters of the camera. These are the same for all videos used, so feel free to hardcode the important values into your program.

Your team has to complete the following tasks:

1.   **Traditional Vision:** Create an algorithm to accurately detect and classify the 3 objects of interest (Cactus, Vehicle, Traffic Sign). You don't have to determine the subclass at this point.
2.   **Deep Learning:** Use a deep learning algorithm to classify traffic signs. The package provided includes a training and validation database of 32x32 RGB images.
3.   **3D Vision:** Determine the 3D positions of the object of interest relative to the camera. Use the center of an object's bounding box to determine the position on the image.

## Hardcore Tasks

There are also 3 hardcore tasks for those who like challenges. These aren't particularly difficult, but they take more work and require you to go a little bit beyond the scope of the practicals.

1.   **Traditional Vision:** Determine the subclasses of Cacti and Vehicles
2.   **Deep Learning:** Of the 55 possible traffic signs, 3 are missing from the training and test datasets. ('*X - Priority*', '*X - Turn left*', '*X - Turn right*') As a result, the neural net trained in task 2 will not be able to classify them properly. Extend your neural network to classify these as well.
3.   **3D Vision:** Determine the absolute pose (4x4 transformation matrix) of the camera as it moves throughout the video. You can safely assume that the pose in the first frame of every video is the identity matrix.

## Evaluation and Score

The basic package also contains annotations (correct answers) in the file **annotations.pickle** and a small python script **evaluate.py** you can use to measure the performance of your algorithm. 

Your homework score will be computed using the same script, albeit on 2 secret videos that you were not provided. The reason for this is to make sure that your algorithm works in new situations as well. The secret videos use the same 2 tablecloths and 3 vehicles, but the traffic signs and the cacti may be different. Not to mention the illumination.

The tasks will be evaluated using the following metrics:

* Task 1 - **Average Precision** (AP): This metric is simply the average of **Recall** (nCorrect / nObject) and **Precision** (nCorrect / nPrediction).
* Tasks 1 HC, 2 and 2 HC - **Classification accuracy**
* Tasks 3 and 3 HC - **RBF error**: This is simple the squared error between the prediction and the correct answer transformed by an RBF (Radial Basis Function) kernel. This means that a perfect answer has a score of 1, a bad answer will result in a score close to 0.

### **Answer format**

The evaluation function takes a single argument: A dictionary that containes your predictions. On the top level this dictionary should look like this:

```python
myAnswers = {
    'video1/rgb/1.jpg' : <<Predictions for the image>>,
    'video1/rgb/2.jpg' : <<Predictions for the image>>,
    ...
    'video4/rgb/10.jpg' : <<Predictions for the image>>,
}
```
It is important that the dictionary key contains the video path, since two videos might have image files with the same name. Also, include all images from all videos in the file (even if you have no predictions), since the evaluation function will look for them! The order of the images does not matter.

A prediction for a single image should also be a dictionary with the following format:
```python
myPred = {
    'poses' : [t_11, t12_, t_13, t_14, ..., t_33, t_34],
    'objects' : [obj_1, obj_2, ... obj_n]
}
```
The key `poses` contains the first three rows of the transformation matrix (the fourth row is always `[0 0 0 1]`). The key `objects` is a list, each element containing a single object prediction. The order of predictions does not matter. A single object prediction is also a list, containing the following elements:
```python
myObjects = [u, v, w, h, classInd, subClassInd, x, y, z]
```

* `(u, v)` are the center coordinates of the object's bounding box, while `(w, h)` are the width and height parameters. All four are expected in pixels @640x480 resolution.
* `(x, y, z)` are the 3D coordinates of the object relative to the camera. They are expected in **meters**.
* `classInd` is the index of the object class in the list `className` (see below). It is between 0 and 2.
* `subClassInd` is the index of the subclass in the appropriate list in `subclassNames` (again, see below). It is between [0-54] for traffic signs, [0-2] for vehicles and [0-3] for cacti.

## Rules

Here are some important rules and guidelines you have to follow:

*   This work is to be done in groups of 3 or 4 people. You can do it with less if you feel confident, but not more.
*   Forming/finding a group is your job. Once you have one, 1 person from the group shold write me a message on teams with the names and neptun codes of the members.
*   If you can't find a group by Sunday, write me and I'll formulate groups with the remaining people.
*   The deadline for the submission is Friday midnight on the 14th week. You can make a late submission until the next Sunday midnight.
*   You can opt out of the homework. In this case you will beed to take the midterm exam. This will be done via teams video chat (oral exam). If you want to take this option, write me a message by Sunday.
*   To pass the homework, you will have to submit a working solution for the 3 basic tasks. The quality of your predictions has to be significantly better than what is achievable by random guessing.

### Offered final grade

To qualify for the offered final grade (and to skip the exams), you have to complete at least one of the hardcore tasks. What this final grade will be depends on the quality of the predictions. 

I cannot specify the criteria exactly at this time, since I don't know how easy/hard this homework is yet. I will, however adhere to the following guidelines:

*   I'm planning to offer Good (4) and Excellent (5) final grades.
*   Those, who completed all 3 hardcore tasks with high quality are gonna get a 5
*   Those, who completed at least 2 hardcore tasks with high quality are gonna get **at least** a 4
*   'High quality' is undefined to create a situation in which teams compete
*   Also, I want to avoid two situations: a., where the criterion is so hard that only a few people manage to get an offered grade; and b., where it is so easy that everyone gets one.
*   My goal is that about 40-50% of all students would get an offered grade, 15-20% getting 5, and 25-30% getting 4. These goals are might change if way more people opt out of homework than I expect.

### Ethics

Copying entire solutions from online sources or each other is plagiarism, and it will be checked using automated tools. There are things that are perfectly okay, such as:
*   Copying small snippets (a few lines) from the OpenCV/PyTorch tutorials or stackoverflow, etc.
*   Appropriating code from the practicals (you can copy the entire thing), especially the deep learning one.
*   Since what is okay and what isn't is a bit subjective, if you are unsure, ask me.

## So, how should we do this?

So, how can you do this homework, especially if you haven't done things like this before? Here are a few tips:

### Environment

For development IDE the easiest is to just use Google Colab. To do this you just have to solve the homework inside this notebook. This is the simplest solution, although it has one drawback: the colab notebook has limited debugging capabilities.

If you want something more powerful, I recommend the [PyCharm](https://www.jetbrains.com/pycharm/) IDE, which is a free and pretty powerful Python development tool.

If you are planning to use PyCharm on Windows, you need to install a Python distribution, since Windows still doesn't come with one (it's 20 effing 20, Microsoft!). I recommend [Anaconda](https://www.anaconda.com/distribution/). Make sure you use Python 3.x and not 2.7.

[Here's a tutorial on how to set it up.](https://www.youtube.com/watch?v=e53lRPmWrMI)

### Collaboration within the team

Since I would strongly discourage teams to collaborate physically in the current situation, I would recommend some methods for remote collaboration.

* First of all, use Teams or similar methods to communicate.
* Second, use git or a similar version control tool to handle multiple team members working on the same project. 
* I strongly recommend creating a private repository for your homework on [Github](https://github.com/) (since you can add exactly 3 collaborators - including you that's a 4 person team). There, you can also create issues and other nice-to-have features to track you development. Getting some experience with version control is an absolute must for any engineer anyways.

Here's a tutorial for git for those who never used something like this before.

To use git from a GUI, I recommend [SmartGit](https://www.syntevo.com/smartgit/) or [Git Extensions](http://gitextensions.github.io/).

**ProTip:** If you use a Colab notebook, make sure to clear the output cells (especially figures and images) before you commit. Otherwise you'll litter in your repository.

[Here is an introduction to git](https://www.freecodecamp.org/news/learn-the-basics-of-git-in-under-10-minutes-da548267cc91/)

### Making a submission

You can make a submission at the appropriate page in the edu portal. The results and leaderboard will also be published here. The results are evaluated around 8pm (CET), so it's pointless to make multiple submission per day.

**Note**: Your submission should be runnable from Colab or PyCharm (if you used any custom libraries, please note it), and it must include the trained neural network model file from task 2. Also, make sure that only the code required for evaluation is ran (you can use a control variable to skip training code).

### Further resources

[Python tutorials](https://docs.python.org/3/tutorial/)

[OpenCV tutorials](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html)

[PyTorch tutorials](https://pytorch.org/tutorials/)




# Solution
## Download dataset

In [13]:
# Homework dataset
!wget http://deeplearning.iit.bme.hu/CVS/HW.zip
!unzip -qq HW.zip
!rm HW.zip

#Traffic Sign Classification set
!wget http://deeplearning.iit.bme.hu/CVS/trafficSignsHW.zip
!unzip -qq trafficSignsHW.zip
!rm trafficSignsHW.zip

# Templates
!wget https://github.com/AndyLightning/SZL-Work/raw/master/Faces.zip
!unzip -qq Faces.zip
!rm Faces.zip

# Best Deep Learning Model
!wget https://github.com/AndyLightning/SZL-Work/raw/Final/model_Final.pth

--2020-05-20 17:43:42--  http://deeplearning.iit.bme.hu/CVS/HW.zip
Resolving deeplearning.iit.bme.hu (deeplearning.iit.bme.hu)... 152.66.243.112
Connecting to deeplearning.iit.bme.hu (deeplearning.iit.bme.hu)|152.66.243.112|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14446460 (14M) [application/zip]
Saving to: ‘HW.zip’

HW.zip              100%[===================>]  13.78M  9.00MB/s    in 1.5s    

2020-05-20 17:43:45 (9.00 MB/s) - ‘HW.zip’ saved [14446460/14446460]

replace HW/annotations.pickle? [y]es, [n]o, [A]ll, [N]one, [r]ename: --2020-05-20 17:44:02--  http://deeplearning.iit.bme.hu/CVS/trafficSignsHW.zip
Resolving deeplearning.iit.bme.hu (deeplearning.iit.bme.hu)... 152.66.243.112
Connecting to deeplearning.iit.bme.hu (deeplearning.iit.bme.hu)|152.66.243.112|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 175675617 (168M) [application/zip]
Saving to: ‘trafficSignsHW.zip’

trafficSignsHW.zip   10%[=>                  ]  18.3

KeyboardInterrupt: ignored

## Folder example

Get all subfolders in a directory

```
import os
myFolderList = [f.path for f in os.scandir(path) if f.is_dir()]
```

Get all files with extension in a directory

```
import glob
import re

def sorted_nicely( l ):
    """ Sort the given iterable in the way that humans expect."""
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ]
    return sorted(l, key = alphanum_key)

names = sorted_nicely(glob.glob1(path, "*.extension"))
```

### Class names


In [0]:
classNames = ['traffic sign', 'vehicle', 'cactus']
subclassNames = [
    ['Bump', 'Bumpy road', 'Bus stop', 'Children', 'Crossing (blue)', 'Crossing (red)', 'Cyclists',
     'Danger (other)', 'Dangerous left turn', 'Dangerous right turn', 'Give way', 'Go ahead', 'Go ahead or left',
     'Go ahead or right', 'Go around either way', 'Go around left', 'Go around right', 'Intersection', 'Limit 100',
     'Limit 120', 'Limit 20', 'Limit 30', 'Limit 50', 'Limit 60', 'Limit 70', 'Limit 80', 'Limit 80 over',
     'Limit over', 'Main road', 'Main road over', 'Multiple dangerous turns', 'Narrow road (left)',
     'Narrow road (right)', 'No entry', 'No entry (both directions)', 'No entry (truck)', 'No stopping', 'No takeover',
     'No takeover (truck)', 'No takeover (truck) end', 'No takeover end', 'No waiting', 'One way road',
     'Parking', 'Road works', 'Roundabout', 'Slippery road', 'Stop', 'Traffic light', 'Train crossing',
     'Train crossing (no barrier)', 'Wild animals', 'X - Priority', 'X - Turn left', 'X - Turn right'],
    ['SUV','truck','plane'],
    ['happy','sad','angry','evil']
]

### Display the first images

In [0]:

colors = [(0,0,255),(255,0,255),(0,255,0)]

def drawBBs(BBs, img):
    img = cv2.resize(img, (1280, 960))
    for BB in BBs:
        u = BB[0]*2
        v = BB[1]*2
        w = BB[2]*2
        h = BB[3]*2
        c = BB[4]
        sc = BB[5]
        x = BB[6]
        y = BB[7]
        z = BB[8]
        s = (max(0,u - w // 2),max(0,v - h // 2))
        e = (u + w // 2,v + h // 2)
        cv2.rectangle(img, s, e, colors[c], 1)
        tl = (s[0], s[1]+15)
        bl = (s[0], e[1]-5)
        cv2.putText(img,subclassNames[c][sc],tl,cv2.FONT_HERSHEY_COMPLEX_SMALL,0.75,colors[c])
        coords = "(%.2f, %.2f, %.2f)" % (x,y,z)
        cv2.putText(img,coords,bl,cv2.FONT_HERSHEY_COMPLEX_SMALL,0.65,colors[c])
    
    return img

import pickle
import cv2
import matplotlib.pyplot as plt
#This way it doesn't try to open a window un the GUI - works in python notebook
%matplotlib inline

# Read images
img = cv2.imread("HW/g1/rgb/1.jpg")
depth = cv2.imread("HW/g1/depth/1.png", -1)

# Read annotations
file = open('HW/annotations.pickle','rb')
annotations = pickle.load(file)

# Visualization
depth = depth / 5000.0
img = drawBBs(annotations["HW/g1/rgb/1.jpg"]["objects"], img)
img_rgb = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

# Figure with subplots
plt.figure(figsize=(30,30))
plt.subplot(1,2,1)
plt.imshow(img_rgb)
plt.subplot(1,2,2)
plt.imshow(depth,cmap='gray')

#Célmappák Beállításához

In [0]:
import glob
import re
import cv2
import numpy as np
import matplotlib.pyplot as plt
import imutils

 
def sorted_nicely( l ):
    """ Sort the given iterable in the way that humans expect."""
    convert = lambda text: int(text) if text.isdigit() else text
    alphanum_key = lambda key: [ convert(c) for c in re.split('([0-9]+)', key) ]
    return sorted(l, key = alphanum_key)


###Itt kéne állítani###
names1=sorted_nicely(glob.glob1('HW/g1/rgb/', "*.jpg"))
names2=sorted_nicely(glob.glob1('HW/g2/rgb/', "*.jpg"))
names3=sorted_nicely(glob.glob1('HW/g3/rgb/', "*.jpg"))
names4=sorted_nicely(glob.glob1('HW/g4/rgb/', "*.jpg"))

allNames=[]
allTruth=[]

###Itt###
cntr=0
for i in names1:
  allNames.append(names1[cntr])
  allTruth.append(cntr<3)
  cntr+=1
cntr=0
for i in names2:
  allNames.append(names2[cntr])
  allTruth.append(cntr<3)
  cntr+=1
cntr=0
for i in names3:
  allNames.append(names3[cntr])
  allTruth.append(cntr<3)
  cntr+=1
cntr=0
for i in names4:
  allNames.append(names4[cntr])
  allTruth.append(cntr<3)
  cntr+=1

###És itt###
allDestination=[]
for i in names1:
  allDestination.append("HW/g1/rgb/"+i)
for i in names2:
  allDestination.append("HW/g2/rgb/"+i)
for i in names3:
  allDestination.append("HW/g3/rgb/"+i)
for i in names4:
  allDestination.append("HW/g4/rgb/"+i)

#Andris Functions

In [0]:


###Descriptorok
path="myTemplates/{}/{}/"
def getDescC(clasS,subClass):

  img1s=[]
  img1s.append(cv2.cvtColor(cv2.imread(path.format(2,0)+"X.PNG"), cv2.COLOR_BGR2RGB))
  img1s.append(cv2.cvtColor(cv2.imread(path.format(2,1)+"X.PNG"), cv2.COLOR_BGR2RGB))
  img1s.append(cv2.cvtColor(cv2.imread(path.format(2,2)+"X.PNG"), cv2.COLOR_BGR2RGB))
  img1s.append(cv2.cvtColor(cv2.imread(path.format(2,3)+"X.PNG"), cv2.COLOR_BGR2RGB))
  gray1=[]
  cntr = 0
  for i in img1s:
    gray1.append(cv2.cvtColor(img1s[cntr], cv2.COLOR_BGR2RGB))
    cntr+=1
  detector=cv2.AKAZE_create()
  #Kulcspontok és descriptorok meghatározása
  kp1=[]
  desc1=[]
  cntr = 0
  for i in img1s:
    help1,help2 = detector.detectAndCompute(gray1[cntr], None)
    kp1.append(help1)
    desc1.append(help2)
    cntr+=1
  return kp1,desc1
def getDesc(clasS,subClass):
  imgNames = sorted_nicely(glob.glob1(path.format(clasS,subClass), "*.PNG"))
  img1s=[]
  for i in imgNames:
      img1s.append(cv2.cvtColor(cv2.imread(path.format(clasS,subClass)+i), cv2.COLOR_BGR2RGB))
  gray1=[]
  cntr = 0
  for i in imgNames:
    gray1.append(cv2.cvtColor(img1s[cntr], cv2.COLOR_BGR2RGB))
    cntr+=1
  can=[]
  cntr = 0
  for i in imgNames:
    can.append(cv2.Canny(gray1[cntr], 50,120))
    cntr+=1
  detector=cv2.AKAZE_create()
  #Kulcspontok és descriptorok meghatározása
  kp1=[]
  desc1=[]
  cntr = 0
  for i in imgNames:
    help1,help2 = detector.detectAndCompute(can[cntr], None)
    kp1.append(help1)
    desc1.append(help2)
    cntr+=1
  return kp1,desc1


kp00,desc00=getDesc(0,0)
kp10,desc10=getDesc(1,0)
kp11,desc11=getDesc(1,1)
kp12,desc12=getDesc(1,2)
kp20,desc20=getDesc(2,0)
kp21,desc21=getDesc(2,1)
kp22,desc22=getDesc(2,2)
kp23,desc23=getDesc(2,3)
kp24,desc24=getDesc(2,4)


#Kontúrokat keresek
def getArea(img):
  contours, hierarchy = cv2.findContours(solution2, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
  area=0
  for cnt in contours:
    area+=cv2.contourArea(cnt)
  return area

def MMaster(clasS, subClass, img2): #####Friss kommentek vannak a gyorsítás miatt!!!!
  u=0
  v=0
  w=0
  h=0
  found=False
  path="myTemplates/{}/{}/"
  imgNames = sorted_nicely(glob.glob1(path.format(clasS,subClass), "*.PNG"))
  img1s = []
  for i in imgNames:
    img1s.append(cv2.cvtColor(cv2.imread(path.format(clasS,subClass)+i), cv2.COLOR_BGR2RGB))

  gray1=[]
  cntr = 0
  #for i in imgNames:
    #gray1.append(cv2.cvtColor(img1s[cntr], cv2.COLOR_BGR2RGB))
    #cntr+=1
  gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
  Canny2=cv2.Canny(gray2,50,120)
  """
  if(clasS==2):
    gray2=cv2.Canny(gray2,50,120)
    cntr = 0
    for i in imgNames:
      gray1[cntr]=cv2.Canny(gray1[cntr],50,120)
      cntr+=1
  """
  # ORB
  #detector = cv2.ORB_create(2000)
  detector=cv2.AKAZE_create()
  #Kulcspontok és descriptorok meghatározása
  kp1=[]
  desc1=[]
  if (clasS==0):
    kp1=kp00
    desc1=desc00
  elif (clasS==1):
    if(subClass==0):
      kp1=kp10
      desc1=desc10
    if(subClass==1):
      kp1=kp11
      desc1=desc11
    if(subClass==2):
      kp1=kp12
      desc1=desc12
  elif (clasS==2):
    kp1=kp20
    desc1=desc20
  
  kp2, desc2 = detector.detectAndCompute(Canny2, None)

  MIN_MATCH = 4 #minimum hány párosítás kell
  if clasS==2:
    MIN_MATCH=7
  #Flann
  FLANN_INDEX_LSH = 6

  #Szótár - kulcs alapú konténer
  index_params= dict(algorithm = FLANN_INDEX_LSH,
                    table_number = 6,
                    key_size = 12,
                    multi_probe_level = 1)
  search_params=dict(checks=32)
  matcher = cv2.DescriptorMatcher_create(cv2.DescriptorMatcher_BRUTEFORCE_HAMMING)

  # Találjuk meg a 2 legjobb párosítást minden matchre
  imgNames=[]
  imgNames = sorted_nicely(glob.glob1(path.format(clasS,subClass), "*.PNG"))
  matches=[]
  cntr = 0
  for i in imgNames:
    if(len(kp1[cntr])>=2 and len(kp2)>=2):
      matches.append(matcher.knnMatch(desc1[cntr], desc2, 2))
    else:
      imgNames.remove(i)
    cntr+=1
  #Paraméter a pontosságunkhoz
  if (len(matches)==0):
    return img2,False,0,0,0,0,0,0






  ratio = 0.75
  #Próbáld meg egy nagyon picit növelni, hátha.....



  #Nem stimmel:
  
  #Jó párosítások meghatározása
  pre_matches=[]
  cntr = 0
  for i in imgNames:
    pre_matches.append([m[0] for m in matches[cntr] \
                      if len(m) == 2 and m[0].distance < m[1].distance * ratio])
    cntr+=1

  good_matches=len(pre_matches[0])
  cntr=1
  index=0
  for i in imgNames[:-1]:
    if len(pre_matches[cntr]) > good_matches:
      good_matches=len(pre_matches[cntr])
      index=cntr
    cntr+=1
  good_matches = [m[0] for m in matches[index] \
                      if len(m) == 2 and m[0].distance < m[1].distance * ratio]
  #Hány jó párosítást találtunk az "összhalmazból"
  print('good matches:%d/%d' %(len(good_matches),len(matches[index])))

  #0 értékekkel teli listát ad vissza, ami olyan hosszú, mint ahány jó párosításunk van
  matchesMask = np.zeros(len(good_matches)).tolist()


  #Ha több jó párosításunk van, mint ahányat megadunk a MIN_Match-el
  if len(good_matches) > MIN_MATCH:
      #Forrás és célpontok meghatározása
      src_pts = np.float32([ kp1[index][m.queryIdx].pt for m in good_matches ])
      dst_pts = np.float32([ kp2[m.trainIdx].pt for m in good_matches ])
      #Megadja a perspektíva transzformációt (mtrx), és egy maszkot, ami tartalmazza az "inlier" és "outlier" pontokat
      mtrx, mask = cv2.findHomography(src_pts, dst_pts, cv2.RANSAC, 5.0)

      #Pontosság
      accuracy=float(mask.sum())*100 / mask.size
      print("accuracy: %d/%d(%.2f%%)"% (mask.sum(), mask.size, accuracy))
      #Ha a maszk elemeinek összege nagyobb MIN_MATCh-nél
      if mask.sum() > MIN_MATCH:
          found=True
          # Sormátrixot csinálunk
          matchesMask = mask.ravel().tolist()
          #Template képnek a magassága és szélessége
          h,w, = img1s[index].shape[:2]
          #pts-nek megadjuk a template méret sarkait
          pts = np.float32([ [[0,0]],[[0,h-1]],[[w-1,h-1]],[[w-1,0]] ])
          #Célpont meghatározása
          dst = cv2.perspectiveTransform(pts,mtrx)
          u=(dst[0][0][0]+dst[1][0][0]+dst[2][0][0]+dst[3][0][0])/4
          v=(dst[0][0][1]+dst[1][0][1]+dst[2][0][1]+dst[3][0][1])/4
          w=((dst[3][0][0]-dst[0][0][0])+(dst[2][0][0]-dst[1][0][0]))/2
          h=((dst[2][0][1]-dst[3][0][1])+(dst[1][0][1]-dst[0][0][1]))/2
          #Kirajzoljuk a négyzetet körbe
          img2 = cv2.polylines(img2,[np.int32(dst)],True,255,3, cv2.LINE_AA)
          

  #Összehúzott kép
  res = cv2.drawMatches(img1s[index], kp1[index], img2, kp2, good_matches, None, \
                      matchesMask=matchesMask,
                      flags=cv2.DRAW_MATCHES_FLAGS_NOT_DRAW_SINGLE_POINTS)
  return res, found, np.int32(u), np.int32(v), np.int32(w), np.int32(h), clasS, index ###Átírtam, itt eredetileg subClass volt!!!


def getContours(img,imgContour,minArea):
  contours, hierarchy = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
  cntr=0
  for cnt in contours:
    approx=[]
    area=cv2.contourArea(cnt)
    if area>minArea:
      cv2.drawContours(imgContour, contours, -1, (255,0,255),7) 
      peri=cv2.arcLength(cnt,True)
      approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)
      x , y , w, h = cv2.boundingRect(approx)
      #cv2.rectangle(imgContour, (x , y ), (x + w , y + h ), (0, 255, 0), 5)
      cntr+=1
      #cv2.putText(imgContour, "Points: " + str(len(approx)), (x + w + 20, y + 20), cv2.FONT_HERSHEY_COMPLEX, .7,
       #                 (0, 255, 0), 2)
      #cv2.putText(imgContour, "Area: " + str(int(area)), (x + w + 20, y + 45), cv2.FONT_HERSHEY_COMPLEX, 0.7,
       #                 (0, 255, 0), 2)
  return cntr
def getZone(img,imgContour,minArea):
  contours,_ = cv2.findContours(img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
  for cnt in contours:
    area=cv2.contourArea(cnt)
    if (area>minArea):
      cv2.drawContours(imgContour, contours, -1, (255,255,255),cv2.FILLED) 
      peri=cv2.arcLength(cnt,True)
      approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)
      x , y , w, h = cv2.boundingRect(approx)
      print(area)
  return opened  
def getObjects(img,imgContour,minArea):
  blur = cv2.GaussianBlur(img, (5,5), 0)
  _, thresh = cv2.threshold(blur, 20, 255, cv2.THRESH_BINARY)
  dilated = cv2.dilate(thresh, None, iterations=2)
  opened = cv2.morphologyEx(dilated, cv2.MORPH_OPEN, np.ones((2,2))) #new
  #imgs_canny=cv2.Canny(np.copy(opened),50,120) #new
  #imgEro=cv2.erode(opened, kernel, iterations=1) #new
  contours, _ = cv2.findContours(opened, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
  #contours, hierarchy = cv2.findContours(img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
  cntr=0
  ret1=[]
  ret2=[]
  ret3=[]
  ret4=[]
  for cnt in contours:
    approx=[]
    area=cv2.contourArea(cnt)
    if (area>minArea and area <15000):
      cv2.drawContours(imgContour, contours, -1, (255,0,255),1) 
      peri=cv2.arcLength(cnt,False)
      approx = cv2.approxPolyDP(cnt, 0.02 * peri, False)
      x , y , w, h = cv2.boundingRect(approx)

      ret1.append(x)
      ret2.append(y)
      ret3.append(w)
      ret4.append(h)

      cv2.rectangle(imgContour, (x , y ), (x + w , y + h ), (0, 255, 0), 5)

      cntr+=1
  return ret1,ret2,ret3,ret4,(cntr-1)
def isSomething(clas,subC,img):
  bol=False
  bad1=bad2=bad3=False
  redParam=np.int32(0)
  blackParam=np.int32(0)
  area=np.int32(0)
  img2=np.copy(img)
  img3=np.copy(img)
  imgcr=np.copy(img)
  imgcrit1=np.copy(img)
  imgcrit2=np.copy(img)
  dilation1=0
  dilation2=0
  if(clas==1 and subC==0):
    mask1=cv2.inRange(img2,np.array([60, 10, 0]), np.array([160, 30, 30]))
    mask2=cv2.inRange(img2,np.array([0, 0, 0]), np.array([30, 30, 30]))
    mask3=cv2.inRange(img2,np.array([160, 15, 0]), np.array([255, 65, 40]))#Too Bright
  if(clas==1 and subC==2):
    mask1=cv2.inRange(img2,np.array([100, 15, 0]), np.array([200, 65, 40])) #120 15
    mask2=cv2.inRange(img2,np.array([0, 0, 0]), np.array([0, 0, 0]))
  masksum=mask1+mask2
  img3[masksum != [255]]=[0,0,0]
  ###Kritériumterületeseknek:
  if(clas==1 and subC==0):
    imgcr[mask3 != [255]]=[0,0,0]
    imgcr=cv2.morphologyEx(imgcr, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
    imgs_canny=cv2.Canny(imgcr,50,120)
    dilationcr=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    (contours,hierarchy)=cv2.findContours(dilationcr,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      if(area>3000):
        bad3=True
        print("bad3-al van a baj")
    imgcrit1[mask1 != [255]]=[0,0,0]
    imgcrit1=cv2.morphologyEx(imgcrit1, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
    imgs_canny=cv2.Canny(imgcrit1,50,120)
    dilation1=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    isZero=0
    for pic, contour in enumerate(contours):
      isZero+=1
      area=cv2.contourArea(contour)
      redParam=area
      if(area<2700):
        bad1=True
      else:
        bad1=False
        break
        print("Piros area kisebb 2700-mál")
    if (isZero==0):
      bad1=True
      print("Nincs piros kontúr")
    imgcrit2[mask2 != [255]]=[0,0,0]
    imgcrit2=cv2.morphologyEx(imgcrit2, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2)))
    imgs_canny=cv2.Canny(imgcrit2,50,120)
    dilation2=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    x2=dilation2
    contours=0
    (contours,hierarchy)=cv2.findContours(dilation2,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    isZero=0
    for pic, contour in enumerate(contours):
      isZero+=1
      area=cv2.contourArea(contour)
      blackParam=area
      if(area<100):
        bad2=True
      else:
        bad2=False
        break
        print("Fekete area kisebb 100-mál")
    if (isZero==0):
      bad2=True
      print("Nincs fekete kontúr")
  img3=cv2.morphologyEx(img3, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
  imgs_canny=cv2.Canny(img3,50,120)
  dilation=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
  contours=0
  (contours,hierarchy)=cv2.findContours(dilation,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
  big=0
  x=y=w=h=0
  for pic, contour in enumerate(contours):
    peri=cv2.arcLength(contour,True)
    approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
    x , y , w, h = cv2.boundingRect(approx)
    print("Nézzük:")
    if (w>(h*5) or h>(w*3)):
      continue
    print("Méret OK")
    if (bad1 or bad2 or bad3): ###Nem teljesült a kritériumkövetelmény
      print("valami bad")
      continue
    print("Színmennyiség OK")
    area=cv2.contourArea(contour)
    if(area>3000):
      if(big<area):
        big=area
      bol=True

  return bol, dilation, big, np.int(x+w/2),np.int(y+h/2),np.int(w),np.int(h),dilation1,dilation2,redParam

def isSUV(clas,subC,img):
  bol=False
  redParam=0
  blackParam=0
  area=0
  big=0
  m1=0
  m2=0
  m3=0
  m4=0
  p1=[]
  p2=[]
  p3=[]
  p4=[]
  img1=np.copy(img)
  img2=np.copy(img)
  img3=np.copy(img)
  imgcr=np.copy(img)
  imgcrit1=np.copy(img)
  imgcrit2=np.copy(img)
  dilation1=0
  dilation2=0
  if(clas==1 and subC==0):
    mask3=cv2.inRange(np.copy(img2),np.array([200, 15, 0]), np.array([255, 65, 40]))#Too Bright mask3=cv2.inRange(np.copy(img2),np.array([140, 15, 0]), np.array([255, 65, 40]))
  if(clas==1 and subC==2):
    mask1=cv2.inRange(img2,np.array([100, 15, 0]), np.array([200, 65, 40])) #120 15
    mask2=cv2.inRange(img2,np.array([0, 0, 0]), np.array([0, 0, 0]))
  #masksum=mask1+mask2
  #img3[masksum != [255]]=[0,0,0]
  ###Kritériumterületeseknek:
  if(clas==1 and subC==0):
    #Pirosság
    imgcrit1=np.copy(img1)
    imafterKill=np.copy(img1)
    mask1=cv2.inRange(imgcrit1,np.array([85, 4, 0]), np.array([200, 50, 30])) #mask1=cv2.inRange(imgcrit1,np.array([75, 10, 10]), np.array([200, 50, 30]))
    imgcrit1[mask1 != [255]]=[0,0,0]
    imgcrit1=cv2.morphologyEx(imgcrit1, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
    imgs_canny=cv2.Canny(imgcrit1,50,120)
    dilation1=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    contours=[]
    (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      redParam=area
      #print("redParam: ", redParam)
      if(area>3000):
        peri=cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
        x , y , w, h = cv2.boundingRect(approx)
        p1.append(x)
        p2.append(y)
        p3.append(x+w)
        p4.append(y+h)
        cv2.rectangle(img2, (x , y ), (x + w , y + h ), (255, 255, 255), -1)
    img2=cv2.inRange(img2,np.array([250, 250, 250]), np.array([255, 255, 255]))
    img1[img2 != [255]]=[0,0,0]
    #Feketeség -> Lesz Fekete Masksum
    imgcrit2=np.copy(img1)
    mask21=cv2.inRange(np.copy(imgcrit2),np.array([0, 0, 0]), np.array([30, 30, 30]))
    mask22=cv2.inRange(np.copy(imgcrit2),np.array([30, 30, 30]), np.array([60, 60, 90]))
    mask23=cv2.inRange(np.copy(imgcrit2),np.array([60, 60, 60]), np.array([90, 60, 90]))
    mask24=cv2.inRange(np.copy(imgcrit2),np.array([90, 90, 90]), np.array([120, 120, 120]))
    masksum=mask21+mask22+mask23+mask24
    imgcrit2[masksum != [255]]=[0]
    imgcrit2=cv2.morphologyEx(imgcrit2, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2)))
    imgs_canny=cv2.Canny(imgcrit2,50,120)
    dilation2=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    contours=[]
    (contours,hierarchy)=cv2.findContours(dilation2,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      blackParam=area
      if(area>1400):
        #print("blackParam: ", blackParam)
        peri=cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
        x , y , w, h = cv2.boundingRect(approx)
        k1=x+w//2
        k2=y+h//2
        cntr=0
        for i in p1:
          if(p1[cntr] < k1 and k1< p3[cntr] and p2[cntr] < k2 and k2 < p4[cntr] and p2[cntr]!=0):
            cv2.rectangle(img, (p1[cntr]-20 , p2[cntr]-20), (p3[cntr]+20,p4[cntr]+20), (255, 255, 255), -1) #Itt
            m1=(p1[cntr]+p3[cntr])//2
            m2=(p2[cntr]+p4[cntr])//2
            m3=(p3[cntr]-p1[cntr])
            m4=(p4[cntr]-p2[cntr])
            bol=True
            break            
          cntr+=1
    return bol, img, big, m1,m2,m3,m4,img1,dilation1,dilation2,blackParam
def isTruck(clas,subC,img):
  bol=False
  redParam=0
  blackParam=0
  area=0
  big=0
  m1=0
  m2=0
  m3=0
  m4=0
  p1=[]
  p2=[]
  p3=[]
  p4=[]
  img1=np.copy(img)
  img2=np.copy(img)
  img3=np.copy(img)
  imgcr=np.copy(img)
  imgcrit1=np.copy(img)
  imgcrit2=np.copy(img)
  dilation1=0
  dilation2=0
  if(clas==1 and subC==1):
    #Sárgaság
    imgcrit1=np.copy(img1)
    imafterKill=np.copy(img1)
    mask1=cv2.inRange(imgcrit1,np.array([140, 80, 0]), np.array([255, 200, 25])) #mask1=cv2.inRange(imgcrit1,np.array([140, 80, 0]), np.array([255, 200, 30]))
    imgcrit1[mask1 != [255]]=[0,0,0]
    imgcrit1=cv2.morphologyEx(imgcrit1, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
    imgs_canny=cv2.Canny(imgcrit1,50,120)
    dilation1=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    contours=[]
    (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      if(area>5000):
        peri=cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
        x , y , w, h = cv2.boundingRect(approx)
        p1.append(x)
        p2.append(y)
        p3.append(x+w)
        p4.append(y+h)
        cv2.rectangle(img2, (x , y -20), (x + w , y + h +20), (255, 255, 255), -1)
    #Sárgaság
    img2=cv2.inRange(img2,np.array([250, 250, 250]), np.array([255, 255, 255]))
    img1[img2 != [255]]=[0,0,0]
    imgcrit2=np.copy(img1)
    mask2=cv2.inRange(np.copy(imgcrit2),np.array([0, 0, 0]), np.array([30, 30, 30]))
    imgcrit2[mask2 != [255]]=[0]
    imgcrit2=cv2.morphologyEx(imgcrit2, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2)))
    imgs_canny=cv2.Canny(imgcrit2,50,120)
    dilation2=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    contours=[]
    (contours,hierarchy)=cv2.findContours(dilation2,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      blackParam=area
      if(area>1000):
        peri=cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
        x , y , w, h = cv2.boundingRect(approx)
        k1=x+w//2
        k2=y+h//2
        cntr=0
        for i in p1:
          if(p1[cntr] < k1 and k1< p3[cntr] and p2[cntr]-20 < k2 and k2 < (p4[cntr]+30) and p2[cntr]!=0 and k2>200):
            cv2.rectangle(img, (p1[cntr] -20, p2[cntr]-20), (p3[cntr]+20,p4[cntr]+20), (255, 255,255), -1) #Itt
            m1=(p1[cntr]+p3[cntr])//2
            m2=(p2[cntr]+p4[cntr])//2
            m3=(p3[cntr]-p1[cntr])
            m4=(p4[cntr]-p2[cntr])
            bol=True
            break            
          cntr+=1
    return bol, img, big, m1,m2,m3,m4,img1,dilation1,dilation2,blackParam


def isTable(clas,subC,img):
  bol=False
  newOpen=False
  redParam=0
  blackParam=0
  area=0
  big=0
  m1=[]
  m2=[]
  m3=[]
  m4=[]
  p1=[]
  p2=[]
  p3=[]
  p4=[]
  img1=np.copy(img)
  img2=np.copy(img)
  img3=np.copy(img)
  imgcr=np.copy(img)
  imgcrit1=np.copy(img)
  imgcrit2=np.copy(img)
  dilation1=0
  dilation2=0
  if(clas==0):
    #White Everywhere
    imgcrit1=np.copy(img1)
    imafterKill=np.copy(img1)
    mask1=cv2.inRange(imgcrit1,np.array([115, 100, 60]), np.array([160, 145, 140])) #mask1=cv2.inRange(imgcrit1,np.array([115, 100, 60]), np.array([200, 215, 215]))
    imgcrit1[mask1 != [255]]=[0,0,0]
    imgcrit1=cv2.morphologyEx(imgcrit1, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(14,14)))
    imgs_canny=cv2.Canny(imgcrit1,50,120)
    dilation1=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    contours=[]
    (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      if(area>3000):
        print(area)
        peri=cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
        x , y , w, h = cv2.boundingRect(approx)
        p1.append(x)
        p2.append(y)
        p3.append(x+w)
        p4.append(y+h)
        cv2.rectangle(img2, (x , y), (x + w , y + h), (255, 255, 255), -1)
    #Keressünk táblákat
    img2=cv2.inRange(img2,np.array([250, 250, 250]), np.array([255, 255, 255])) 
    img1[img2 != [255]]=[0,0,0]
    imgcrit2=np.copy(img1)
    img3=np.copy(img1)
    mask21=cv2.inRange(np.copy(imgcrit2),np.array([100, 20, 30]), np.array([200, 70, 50]))
    mask22=cv2.inRange(np.copy(imgcrit2),np.array([0, 40, 10]), np.array([30, 90, 40]))
    mask23=cv2.inRange(np.copy(imgcrit2),np.array([120, 100, 0]), np.array([200, 160, 20]))
    masksum=[mask21,mask22,mask23]
    cntrj=1
    for j in masksum:
      imgcrit2=np.copy(img3)
      imgcrit2[j != [255]]=[0]
      imgcrit2=cv2.morphologyEx(imgcrit2, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
      imgs_canny=cv2.Canny(imgcrit2,50,120)
      dilation2=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
      contours=[]
      (contours,hierarchy)=cv2.findContours(dilation2,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
      for pic, contour in enumerate(contours):
        area=cv2.contourArea(contour)
        blackParam=area
        if(area>800 and area<3500):
          print("Area OK")
          peri=cv2.arcLength(contour,True)
          approx = cv2.approxPolyDP(contour, 0.1 * peri, True) ###Ezt átírtam 0.02-ről!!!
          x , y , w, h = cv2.boundingRect(approx)
          k1=x+w//2
          k2=y+h//2
          cntr=0
          for i in p1:
            if(p1[cntr] < k1 and k1< p3[cntr] and p2[cntr] < k2 and k2 < (p4[cntr]) and p2[cntr]!=0):
              cv2.rectangle(img1, (x,y), (x+w//2,y+h//2), (0, 255, 255), 5)
              m1.append((p1[cntr]+p3[cntr])//2)
              m2.append((p2[cntr]+p4[cntr])//2)
              m3.append(p3[cntr]-p1[cntr])
              m4.append(p4[cntr]-p2[cntr])
              bol=True            
            cntr+=1
    return bol, img, big, m1,m2,m3,m4,img1,dilation1,dilation2,blackParam

def isReallyCactus(x,y,r,img):
  bol=False
  redParam=0
  blackParam=0
  area=0
  big=0
  m1=x
  m2=y
  m3=2*r
  m4=2*r
  p1=0
  p2=0
  p3=0
  p4=0
  img1=np.copy(img)
  img2=np.copy(img)
  img3=np.copy(img)
  imgcr=np.copy(img)
  imgcrit1=np.copy(img)
  imgcrit2=np.copy(img)
  dilation1=0
  dilation2=0
  #Valami zöldes trutymó
  imgcrit1=np.copy(img1)
  cv2.rectangle(imgcrit1, (x-60 , y-60), (x + 60 , y + 60), (255, 255, 255), -1)
  imgcrit1=cv2.inRange(imgcrit1,np.array([250,250,250]), np.array([255,255,255]))
  img3[imgcrit1==[0]]=[0,0,0]
  mask1=cv2.inRange(img3,np.array([20, 20, 0]), np.array([70, 70, 30])) #mask1=cv2.inRange(imgcrit1,np.array([140, 80, 0]), np.array([255, 200, 30]))
  imgcrit2[mask1 != [255]]=[0,0,0]
  imgcrit2=cv2.morphologyEx(imgcrit2, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3)))
  imgs_canny=cv2.Canny(imgcrit2,50,120)
  dilation1=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
  contours=[]
  (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
  for pic, contour in enumerate(contours):
    area=cv2.contourArea(contour)
    if(area>800): #800-al egész jó volt
      #print(area)
      peri=cv2.arcLength(contour,True)
      approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
      x , y , w, h = cv2.boundingRect(approx)
      p1=min(x,m1-m3//2)
      p2=min(y,m2-m4//2)
      p3=max(x+w,m1+m3//2)
      p4=max(y+h+20,m2+20+m4//2)
      cv2.rectangle(img, (p1-10, p2-30), (p3+10 , p4+20), (255, 255, 255), -1) #Itt
      bol=True
  return bol, img, big, (p1+p3)//2,(p2+p4)//2,(p3-p1),(p4-p2),img1,dilation1,imgcrit1,blackParam


def isRepzi(clas,subC,img):
  bol=False
  redParam=0
  blackParam=0
  area=0
  big=0
  m1=0
  m2=0
  m3=0
  m4=0
  p1=[]
  p2=[]
  p3=[]
  p4=[]
  img1=np.copy(img)
  img2=np.copy(img)
  img3=np.copy(img)
  imgcr=np.copy(img)
  imgcrit1=np.copy(img)
  imgcrit2=np.copy(img)
  dilation1=0
  dilation2=0
  if(clas==1 and subC==2):
    mask1=cv2.inRange(img2,np.array([100, 15, 0]), np.array([200, 65, 40])) #120 15
    mask2=cv2.inRange(img2,np.array([170, 70, 0]), np.array([200, 140, 50]))
    imgcrit1=np.copy(img1)
    imgcrit1[mask1 != [255]]=[0,0,0]
    imgcrit1=cv2.morphologyEx(imgcrit1, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2)))
    imgs_canny=cv2.Canny(imgcrit1,50,120)
    dilation1=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    contours=[]
    (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      redParam=area
      if(area>3000):
        peri=cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
        x , y , w, h = cv2.boundingRect(approx)
        p1.append(x)
        p2.append(y)
        p3.append(x+w)
        p4.append(y+h)
        cv2.rectangle(img2, (x , y ), (x + w , y + h ), (255, 255, 255), -1)
    img2=cv2.inRange(img2,np.array([250, 250, 250]), np.array([255, 255, 255]))
    img1[img2 != [255]]=[0,0,0]
    imgcrit2=np.copy(img1)
    imgcrit2[mask2 != [255]]=[0]
    imgcrit2=cv2.morphologyEx(imgcrit2, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(2,2)))
    imgs_canny=cv2.Canny(imgcrit2,50,120)
    dilation2=cv2.dilate(imgs_canny,kernel_dil,iterations=1)
    contours=[]
    (contours,hierarchy)=cv2.findContours(dilation2,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    for pic, contour in enumerate(contours):
      area=cv2.contourArea(contour)
      blackParam=area
      if(area>400 and area<3000):
        peri=cv2.arcLength(contour,True)
        approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
        x , y , w, h = cv2.boundingRect(approx)
        k1=x+w//2
        k2=y+h//2
        cntr=0
        for i in p1:
          if(p1[cntr] < k1 and k1< p3[cntr] and p2[cntr] < k2 and k2 < p4[cntr] and p2[cntr]!=0):
            cv2.rectangle(img, (p1[cntr] , p2[cntr]), (p3[cntr],p4[cntr]), (255, 255, 255), -1) #Itt
            m1=(p1[cntr]+p3[cntr])//2
            m2=(p2[cntr]+p4[cntr])//2
            m3=(p3[cntr]-p1[cntr])
            m4=(p4[cntr]-p2[cntr])
            bol=True
            break            
          cntr+=1
    return bol, img, big, m1,m2,m3,m4,img1,dilation1,dilation2,blackParam
def concentrate(num):
  if num<0:
    return 0
  if num>700:
    return 0
  return num
def redTable (img,obje):
  bol=True
  redParam=0
  blackParam=0
  area=0.0
  big=0
  m1=[]
  m2=[]
  m3=[]
  m4=[]
  p1=[]
  p2=[]
  p3=[]
  p4=[]
  ErrFent=[]
  ErrLent=[]
  ErrBal=[]
  ErrJobb=[]
  img1=np.copy(img)
  img2=np.copy(img)
  img3=np.copy(img)
  img4=np.copy(img)
  imgGray=np.copy(img)
  imgGray=cv2.cvtColor(imgGray,cv2.COLOR_RGB2GRAY)
  imgcr=np.copy(img)
  imgcrit1=np.copy(img)
  imgcrit2=np.copy(img)
  dilation1=0
  dilation2=0
  Fekete=[]
  c=0
  d=0
  while(c<480):
    sor=[]
    d=0
    while(d<640):
      sor.append(0)
      d+=1
    Fekete.append(sor)
    c+=1
  Fekete=np.copy(img)
  for i in obje:
    ErrFent.append(concentrate(i[1]-i[3]))
    ErrBal.append(concentrate(i[0]-i[2]))
    ErrLent.append(concentrate(i[1]+i[3]))
    ErrJobb.append(concentrate(i[0]+i[2]))
  mask1 = cv2.inRange(imgGray, np.array([0]), np.array([100]))
  imgcrit1=np.copy(img1)
  imgcrit1[mask1 != [255]]=[0,0,0]
  imgcrit1=cv2.morphologyEx(imgcrit1, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(7,7)))
  imgs_canny=cv2.Canny(mask1,50,120)
  dilation1=cv2.dilate(imgs_canny,np.ones((5,5),np.uint8),iterations=1)
  dilation1=cv2.morphologyEx(dilation1, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(10,10)))
  dilation1=cv2.morphologyEx(dilation1, cv2.MORPH_CLOSE, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(10,10)))
  contours=[]
  (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
  for pic, contour in enumerate(contours):
    area=cv2.contourArea(contour)
    redParam=area
    if(800<area and area<5000):
      peri=cv2.arcLength(contour,True)
      approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
      x , y , w, h = cv2.boundingRect(approx)
      bol=True
      cntr=0
      if(bol and y>50):
        p1.append(x)
        p2.append(y)
        p3.append(x+w)
        p4.append(y+h)
        cv2.rectangle(img2, (x , y ), (x + w , y + h ), (255, 255, 255), -1)
        cv2.putText(img2,(str(area)), (x+5,y+15), cv2.FONT_HERSHEY_COMPLEX_SMALL,1.5,(255, 255, 255), 2)
  img2=cv2.inRange(img2, np.array([250,250,250]), np.array([255,255,255]))
  img3[img2 != [255]]=[0,0,0]
  imgGray=np.copy(img3)
  imgGray=cv2.cvtColor(imgGray,cv2.COLOR_RGB2GRAY)
  imgGray = cv2.inRange(imgGray, np.array([0]), np.array([60]))
  imgGray=cv2.morphologyEx(imgGray, cv2.MORPH_OPEN, cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(7,7)))
  imgs_canny=cv2.Canny(imgGray,50,120)
  dilation1=cv2.dilate(imgs_canny,np.ones((3,3),np.uint8),iterations=1)
  contours=[]
  (contours,hierarchy)=cv2.findContours(dilation1,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
  for pic, contour in enumerate(contours):
    area=cv2.contourArea(contour)
    if(area>3000 and area<20000):
      peri=cv2.arcLength(contour,True)
      approx = cv2.approxPolyDP(contour, 0.02 * peri, True)
      x , y , w, h = cv2.boundingRect(approx)
      cv2.rectangle(imgcr, (x , y ), (x + w , y + h ), (255, 255, 255), -1)
      cv2.rectangle(Fekete, (x , y ), (x + w , y + h ), (255,255,255), -1)
  imgcr=cv2.inRange(imgcr, np.array([250,250,250]), np.array([255,255,255]))
  Fekete=cv2.inRange(Fekete, np.array([250,250,250]), np.array([255,255,255]))
  imgGray=np.copy(img4)
  imgGray[imgcr != [255]]=[0,0,0]
  imgGray=cv2.cvtColor(imgGray,cv2.COLOR_RGB2GRAY)
  img_eq = cv2.equalizeHist(imgGray)
  hist2 = cv2.calcHist([img_eq], [0], None, [256], [0,256])
  Ranger=cv2.inRange(img_eq, np.array([0]), np.array([120]))
  Ranger[Fekete == 0]=0
  detected_circles = cv2.HoughCircles(Ranger,cv2.HOUGH_GRADIENT, 1, 25, param1 = 40, param2 = 20, minRadius = 9, maxRadius = 20) #40-20 egész jó volt
  if detected_circles is not None:     
      detected_circles = np.uint16(np.around(detected_circles))     
      for pt in detected_circles[0, :]:
          a, b, r = pt[0], pt[1], pt[2] 
          img=cv2.circle(img, (a, b), r, (128,255,255), -1)
          m1.append(a)
          m2.append(b)
          m3.append(2*r)
          m4.append(2*r)

  Ranger2=np.copy(Ranger)
  (contours,hierarchy) = cv2.findContours(Ranger, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
  coordinates = []
  for cnt in contours:
    area=cv2.contourArea(contour)
    approx = cv2.approxPolyDP(cnt, 0.07 * cv2.arcLength(cnt, True), True)
    x , y , w, h = cv2.boundingRect(approx)
    if (len(approx) == 3 and (w*h)<890 and (w*h)>700):
        #cv2.drawContours(img, [cnt], 0, (128, 255, 255), -1) #Itt
        #cv2.putText(img,(str(w*h)), (x+5,y+15), cv2.FONT_HERSHEY_COMPLEX_SMALL,1.5,(0, 0, 0), 2)
        m1.append(x+w//2)
        m2.append(y+h//2)
        m3.append(w)
        m4.append(h)
  (contours,hierarchy) = cv2.findContours(Ranger, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
  coordinates = []
  for cnt in contours:
    area=cv2.contourArea(contour)
    if(area>5000):
      peri=cv2.arcLength(contour,True)
      approx = cv2.approxPolyDP(contour, 0.07 * peri, True)
      x , y , w, h = cv2.boundingRect(approx)
      cv2.rectangle(Ranger2, (x , y ), (x + w , y + h ), (0,0,0), -1)
  return bol, img, big, m1,m2,m3,m4,Ranger2,Ranger,Ranger2,blackParam

def kozl(myImg):
  bol=False
  m1=[]
  m2=[]
  m3=[]
  m4=[]
  i=np.copy(myImg)
  img=np.copy(i)
  img2=img.reshape((-1,3))
  img2=np.float32(img2)
  criteria=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,10,1.0)
  k=3
  attempts=10
  ret,label,center=cv2.kmeans(img2,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
  center=np.uint8(center)
  res=center[label.flatten()]
  res2=res.reshape((img.shape))
  gray=cv2.cvtColor(res2,cv2.COLOR_RGB2GRAY)
  bined=cv2.inRange(gray,np.array([0]),np.array([128]))
  contours,_ = cv2.findContours(bined, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
  for cnt in contours:
    area=cv2.contourArea(cnt)
    peri=cv2.arcLength(cnt,True)
    approx = cv2.approxPolyDP(cnt, 0.02 * peri, True)
    x , y , w, h = cv2.boundingRect(approx)
    if(area>200.0 and area<3000.0 and (x+w//2)<620 and (y+h//2)<420 and y>20 and w<np.int(1.3*h) and h<np.int(1.3*w)):
      bol=True
      m1.append(x+w//2)
      m2.append(y+h//2)
      m3.append(w)
      m4.append(h)
      cv2.drawContours(img, cnt, -1, (0,255,255),-1)
      #cv2.putText(img,str(area),(x+5,y+10),cv2.FONT_HERSHEY_COMPLEX_SMALL,1.25,(255,0,0))
  return bol, img, m1,m2,m3,m4

# Andris + Vektor Work

In [0]:
import yaml
import math
%matplotlib inline
plt.figure(figsize=(30,300))
from PIL import Image
# Read first frame
myAnswers={} #Evaluationhoz
myPred={}
myObjects=[]
u=[]  #Feltöltéshez
v=[]
w=[]
h=[]
imgsRgb=[] #Számításokhoz
imgsRong=[] #Rongáláshoz
imgSeg=[]
kernel_dil=np.ones((20,20),np.uint8)
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(3,3))

cntr=0
for i in allNames:
  imgsRgb.append(cv2.imread(allDestination[cntr]))
  imgsRgb[cntr]=cv2.cvtColor(imgsRgb[cntr],cv2.COLOR_BGR2RGB)
  imgsRong.append(np.copy(imgsRgb[cntr]))
  cntr+=1


#Arculás
faces=[]
faced=[]
facedx=[]
faces.append(cv2.imread('Faces/0.PNG'))
faces.append(cv2.imread('Faces/1.PNG'))
faces.append(cv2.imread('Faces/2.PNG'))
faces.append(cv2.imread('Faces/3.PNG'))
faced.append(cv2.imread('Faces/Faced/0.png'))
faced.append(cv2.imread('Faces/Faced/1.png'))
faced.append(cv2.imread('Faces/Faced/2.png'))
faced.append(cv2.imread('Faces/Faced/3.png'))
facedx.append(cv2.imread('Faces/Faced/H2.png'))
facedx.append(cv2.imread('Faces/Faced/S2.png'))
faced[0]=cv2.cvtColor(faced[0], cv2.COLOR_BGR2GRAY)
faced[1]=cv2.cvtColor(faced[1], cv2.COLOR_BGR2GRAY)
faced[2]=cv2.cvtColor(faced[2], cv2.COLOR_BGR2GRAY)
faced[3]=cv2.cvtColor(faced[3], cv2.COLOR_BGR2GRAY)
facedx[0]=cv2.cvtColor(facedx[0], cv2.COLOR_BGR2GRAY)
facedx[1]=cv2.cvtColor(facedx[1], cv2.COLOR_BGR2GRAY)
#Detect Faces
cntr=0
cntr2=0
invFaces=[]
for i in faces:
  print('asd')
  img=np.copy(faces[cntr])
  gray=np.copy(faces[cntr])
  gray= cv2.cvtColor(gray, cv2.COLOR_RGB2GRAY)
  gray = cv2.blur(gray, (3, 3))
  #plt.imshow(gray)
  detected_circles = cv2.HoughCircles(gray,cv2.HOUGH_GRADIENT, 1, 15, param1 = 80, param2 = 40, minRadius = 7, maxRadius = 40) #70-35 egész jó volt
  if detected_circles is not None: 
    # Convert the circle parameters a, b and r to integers. 
    detected_circles = np.uint16(np.around(detected_circles)) 
    for pt in detected_circles[0, :]:
        mask=np.copy(img)
        maskhelp=np.copy(img) 
        a, b, r = pt[0], pt[1], pt[2] 
        mask=cv2.circle(mask, (a, b), r, (255,255,255), -1)
        mask=cv2.inRange(mask,np.array([254,254,254]), np.array([255,255,255]))
        maskhelp[mask != [255]]=[0,0,0]
        faces[cntr]=(maskhelp[(b-r):(b+r),(a-r):(a+r)])
        faces[cntr]=cv2.cvtColor(faces[cntr], cv2.COLOR_RGB2GRAY)
        faces[cntr] = cv2.morphologyEx(faces[cntr], cv2.MORPH_OPEN, np.ones((2,2)))
        faces[cntr] = cv2.equalizeHist(faces[cntr])
        faces[cntr]=cv2.inRange(faces[cntr],np.array([50]), np.array([255]))
        length=min(faces[cntr].shape[1],faces[cntr].shape[0])
        faces[cntr] = cv2.resize(faces[cntr], (length,length), interpolation = cv2.INTER_AREA)
        invFaces.append(np.copy(faces[cntr]))
        invFaces[cntr][invFaces[cntr]!=0]=0
        invMask=np.copy(invFaces[cntr])
        invMask=cv2.circle(invMask, (r, r), r-10, (255), -1)
        invFaces[cntr][faces[cntr]==0]=255
        invFaces[cntr][invMask==0]=0
        invFaces[cntr]=cv2.circle(invFaces[cntr], (r, r), r, (0), 5)
        cntr2+=1    
  cntr+=1


kernel = np.ones((8,8), np.uint8)




#Ezt Használjuk Igazán
cntr=0
cntr2=0
cntr3=0
print('bármi kerestetik')
for i in allNames:
  myPred={}
  myObjects=[]  
  img=np.copy(imgsRong[cntr])
  gray=np.copy(img)
  gray= cv2.cvtColor(gray, cv2.COLOR_RGB2GRAY)
  gray = cv2.blur(gray, (3, 3))
  detected_circles = cv2.HoughCircles(gray,cv2.HOUGH_GRADIENT, 1, 25, param1 = 90, param2 = 45, minRadius = 7, maxRadius = 50) #90-45 egész jó volt
  c0=[]
  c1=[]
  c2=[]
  c3=[]
  if detected_circles is not None:     
      detected_circles = np.uint16(np.around(detected_circles))     
      for pt in detected_circles[0, :]:
          a, b, r = pt[0], pt[1], pt[2] 
          Croped=np.copy(img)
          p1=b-r
          p2=b+r
          p3=a-r
          p4=a+r
          if(p1>1000):
            p1=0
          if(p3>1000):
            p3=0
          Crop=Croped[(p1):(p2),(p3):(p4)]
          Crop=cv2.cvtColor(Crop, cv2.COLOR_RGB2GRAY)
          Crop=cv2.inRange(Crop,np.array([80]), np.array([255]))
          essence=(np.int(cv2.countNonZero(Crop))>np.int(0.9*(r*r*3)))
          
          bol,imghelp,big,m1,m2,m3,m4,i1,i2,i3,redParam=isReallyCactus(a,b,r,img)
          if (essence==True and m1!=0 and m2!=0 and m3!=0 and m4!=0):


            #Osztályozzuk
            mask=np.copy(imgsRong[cntr])
            maskhelp=np.copy(imgsRong[cntr]) 
            mask=cv2.circle(mask, (a, b), r, (255,255,255), -1)
            mask=cv2.inRange(mask,np.array([250,250,250]), np.array([255,255,255]))
            maskhelp[mask != [255]]=[0,0,0]
            maskhelp=cv2.Canny(maskhelp,50,120)
            """
            #KMeans
            img11=np.copy(imgsRgb[cntr])
            img22=img11.reshape((-1,3))
            img22=np.float32(img22)
            criteria=(cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,10,1.0)
            k=2
            attempts=10
            ret,label,center=cv2.kmeans(img22,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
            center=np.uint8(center)
            res=center[label.flatten()]
            res2=res.reshape((img11.shape))
            gray=cv2.cvtColor(res2,cv2.COLOR_RGB2GRAY)
            bined=cv2.inRange(gray,np.array([0]),np.array([128]))
            maskhelp=np.copy(bined)
            """
            imgsCrop=maskhelp[(b-r):(b+r),(a-r):(a+r)]
            #imgsCrop=cv2.cvtColor(imgsCrop, cv2.COLOR_RGB2GRAY)
            if(True):
              ter=1000
              cntr3=0
              num=0
              for j in facedx:
                print("Mosoly::",cv2.countNonZero(np.copy(facedx[0])))
                print("Szomoly::",cv2.countNonZero(np.copy(facedx[1])))
                simg=np.copy(imgsCrop)
                #simg = cv2.morphologyEx(simg, cv2.MORPH_OPEN, np.ones((2,2)))
                #simg = cv2.equalizeHist(simg)
                #simg=cv2.inRange((simg),np.array([128]), np.array([255]))
                invCopy=np.copy(invFaces[cntr3])
                invCopy = cv2.dilate(invCopy, kernel, iterations=1)
                w1=simg.shape[1]
                h1=simg.shape[0]
                dimension = (w1, h1) 
                helper=np.copy(j)
                helper= cv2.resize(helper, dimension, interpolation = cv2.INTER_AREA) #Ez új méretező
                eTer=cv2.countNonZero(helper)
                #w1=j.shape[1]
                #h1=j.shape[0]
                #dimension = (w1, h1) 
                #simg = cv2.resize(simg, dimension, interpolation = cv2.INTER_AREA)
                #Szem terület arány:
                sized=np.copy(simg)
                o1=np.int(w1*0.25)
                o2=np.int(h1*0.13)
                o3=np.int(w1*0.75)
                o4=np.int(h1*0.43)
                #print("o1:",o1)
                #print("o2:",o2)
                #print("o3:",o3)
                #print("o4:",o4)
                sized=sized[o2:o4,o1:o3]
                xRea=w1*h1
                xRea=xRea*0.5
                xRea=xRea*0.3
                szem=(cv2.countNonZero(sized)/xRea)
                #print("xRea:",xRea)
                #print("sized:",sized)
                #Idáig
                solution=simg-helper
                solution=cv2.circle(solution, (w1//2, h1//2), min(w1,h1)//2, (0), 8)
                solution2=np.copy(simg)
                mask=np.zeros((h1, w1))
                cv2.rectangle(mask, (0,0), (w1,h1//2), (255), -1)
                mask[simg==255]=0
                cv2.rectangle(mask, (0,h1//2), (w1,h1), (0), -1)
                solution2[simg==255]=0
                solution2[simg==0]=255
                #facedx[cntr3] = cv2.resize(facedx[cntr3], dimension, interpolation = cv2.INTER_AREA)
                helper[solution2==255]=0
                cv2.rectangle(solution2,(np.int(w1*0.25),np.int(h1*0.13)),(np.int(w1*0.75),np.int(h1*0.43)),0,-1)
                back=cv2.countNonZero(helper)
                area=cv2.countNonZero(helper)/cv2.countNonZero(j)
                veszt=eTer-cv2.countNonZero(helper)
                if(num==1):
                  veszt=veszt*1.05
                asd=np.copy(facedx[cntr3])
                print('Ter:', ter)
                print('Veszt:', veszt)
                if(veszt<ter):
                  print("Got in")
                  print("with:",veszt)
                  ter=veszt
                  num=cntr3
                cv2.putText(helper, str(szem), (5, 10), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (255))
                cv2.putText(helper, str(veszt), (5, 20), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (255))
                #cv2.putText(helper, str(back), (5, 30), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (255))
                #cv2.putText(helper, str(cv2.countNonZero(simg)), (30, 10), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (255))
                #cv2.putText(solution2, str((cv2.countNonZero(solution2))), (5, 10), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (0))
                #cv2.putText(asd, str((cv2.countNonZero(facedx[cntr3]))), (5, 10), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (255))
                #cv2.putText(mask, str((cv2.countNonZero(mask))-800), (5, 10), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (0))
                #cv2.putText(simg, str((cv2.countNonZero(simg))), (5, 10), cv2.FONT_HERSHEY_COMPLEX_SMALL,0.5, (255))
                cntr3+=1
                if(False):
                  cntr2+=1
                  plt.subplot(60,3,cntr2*3+1)
                  plt.imshow(simg,cmap='gray')
                  plt.subplot(60,3,cntr2*3+2)
                  plt.imshow(helper,cmap='gray')
                  plt.subplot(60,3,cntr2*3+3)
                  plt.imshow(j,cmap='gray')
                if(num==1):
                  if(szem>0.2):
                    num=2
                if(num==0):
                  num=0
                  if(szem>0.2):
                    num=3      
            print("Siker: ",cv2.countNonZero(Crop), np.int(0.8*(r*r*3)), essence)
            myObjects.append([m1,m2,m3,m4,2,num,0,0,0])
          elif(a!=0 and b!=0 and r!=0):
            print(m1,m2,m3,m4)
            print("Fail: ",cv2.countNonZero(Crop), np.int(0.8*(r*r*3)), essence)
            myObjects.append([a,b,r*2,r*2,0,0,0,0,0])
            img=cv2.rectangle(img, (a-r , b-r ), (a + r , b + r ), (255, 255, 255), -1)

  #Tablak
  bol,imghelp,p0,p1,p2,p3=kozl(img)
  img=imghelp
  if (bol):
    cnt=0
    for i in p0:
      myObjects.append([p0[cnt],p1[cnt],p2[cnt],p3[cnt],0,0,0,0,0])
      cnt+=1
  #Truck
  bol,imghelp,big,p0,p1,p2,p3,i1,i2,i3,redParam=isTruck(1,1,img)
  img=imghelp
  if (bol):
    myObjects.append([p0,p1,p2,p3,1,1,0,0,0])
  #ITS A PLANEEEEE AVAGY A SOKADIK HAJNALI PROGRAMOZÁSNÁL....
  bol,imghelp,big,p0,p1,p2,p3,i1,i2,i3,redParam=isRepzi(1,2,img)
  img=imghelp
  if (bol):
    myObjects.append([p0,p1,p2,p3,1,2,0,0,0])
  #SUV
  bol,imghelp,big,p0,p1,p2,p3,i1,i2,i3,redParam=isSUV(1,0,img)
  img=imghelp
  if (bol and p1>200):
    myObjects.append([p0,p1,p2,p3,1,0,0,0,0])
  """
  #More Tables
  yourObject=myObjects.copy()
  bol,imghelp,big,p0,p1,p2,p3,i1,i2,i3,redParam=redTable(img,yourObject)
  c=0
  for j in p0:
    myObjects.append([p0[c],p1[c],p2[c],p3[c],0,0,0,0,0])
    c+=1
  img=imghelp
  imgSeg.append(np.copy(imghelp))
  """
  myPred["objects"] = myObjects
  myPred["poses"] = [0,0,0,0,0,0,0,0,0,0,0,0] 
  print("allDestination[cntr]",myObjects)
  myAnswers[allDestination[cntr]]=myPred

  #plt.subplot(24,3,cntr+1)
  cntr2+=1
  #plt.imshow(drawBBs(myAnswers[allDestination[cntr]]["objects"],imgsRgb[cntr]))
  cntr+=1


with open("HW/calibration.yaml") as file:
  file.readline()
  file.readline()
  documents = yaml.load(file)
  for item,data in documents.items():
    print(item, ':', data)
    if item == 'image_height':
      image_height = data
    elif item == 'image_width':
      image_width = data
    elif item == 'camera_matrix':
      for item_2,data_2 in data.items():
        if item_2 == 'data':
          camera_matrix = data_2
    elif item == 'distortion_coefficients':
      for item_2,data_2 in data.items():
        if item_2 == 'data':
          distortion_coefficients = data_2
fx = camera_matrix[0]
px = camera_matrix[2]
fy = camera_matrix[4]
py = camera_matrix[5]
camera_matrix = [camera_matrix[0:3], camera_matrix[3:6], camera_matrix[6:9]]
camera_matrix = np.array(camera_matrix)
distortion_coefficients = np.array(distortion_coefficients)

for item,data in myAnswers.items():
  item = item[:-3]
  first,second = item.split("rgb")
  item = first + 'depth' + second + 'png'
  img = cv2.imread(item,-1)
  img_2 = cv2.undistort(img, camera_matrix, distortion_coefficients, None, camera_matrix)
  map_u, map_v = cv2.initUndistortRectifyMap(camera_matrix, distortion_coefficients, None, camera_matrix, (image_width,image_height), cv2.CV_32FC1)
  for item_2,data_2 in data.items():
    if item_2 == "objects":
      for myobject in data_2:
        u = myobject[0]
        v = myobject[1]
        u_new = map_u[v,u]
        v_new = map_v[v,u]
        print(int(v_new),int(u_new))
        #solution where depth = z
        z = img[int(v_new),int(u_new)]
        z = z
        x = (z*u_new-z*px)/fx
        y = (z*v_new-z*py)/fy
        y = -y
        #solution where depth = sqrt(z^2+x^2+y^2)
        '''
        d = img[int(v_new),int(u_new)]
        a = fy**2+(v**2-py**2)-((u**2-px**2)*(v**2-py**2))/(u**2+fx**2-px**2)
        b = d**2*((v**2-py**2)-((u**2-px**2)*(v**2-py**2))/(u**2+fx**2-px**2))
        print(a)
        print(b)
        y = b/a
        if y < 0:
          y = -math.sqrt(-y)
        else:
          y = math.sqrt(y)
        x = (-((y**2-d**2)*(u**2-px**2))/(u**2+fx**2-px**2))
        if x < 0:
          x = -math.sqrt(-x)
        else:
          x = math.sqrt(x)
        z = math.sqrt(d**2-x**2-y**2)
        '''
        z = z/1000
        y = y/1000
        x = x/1000
        print(x, y, z)
        myobject[6] = x
        myobject[7] = y
        myobject[8] = z
print(fx)
print(fy)
print(px)
print(py)

"""
cntr=0
for i in imgsRgb:
  plt.subplot(24,3,cntr+1)
  plt.imshow(drawBBs(myAnswers[allDestination[cntr]]["objects"], i))
  cntr+=1
"""

#Barni


In [14]:
import glob
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

'''plt.figure(figsize=(30,30))
plt.subplot(1,3,1)
plt.imshow(img1)
plt.subplot(1,3,2)
plt.imshow(img2)'''

'''
A = np.eye(4)
print(A)

objectsPrev = []
myMatrix = []
src = []
dst = []
#print(np.array(myAnswers))
#x = myAnswers.items()
#print('with item():',x)
objparamPrev = []
for imgname, objects in myAnswers.items():
  print ('\n',imgname, ' : ')

  for objects2 in objects.items():
    if objects2[0] == 'objects':
      objparam = np.array(objects2[1][:][:])
      if(objparamPrev == []):
        print('first')
        objparamPrev = objparam
        A = np.eye(4)
        myMatrix.append(A)
        print(np.array(myMatrix).reshape(-1,4,4))
      else:
        objparam = np.array(objects2[1][:][:])
        #print(objparam[:])




        #give src the x,y,z params
        for row in objparam:
          #print('first row:', row)
          print('\ncoords of object:')
          print(row[6:9])
          for row2 in objparamPrev:
            #print('second row:', row2)
            distu = row[0]-row2[0]
            distv = row[1]-row2[1]
            
            #print('distu, distv:', distu, distv)
            if abs(distu) < 100 and abs(distv)<100:
              if row[4] == row2[4]:
                print('possible match:')
                print(row2[6:9])
            

              #src.append((objparamPrev[match][6], objparam[match][7], objparam[match][8]))
              #dst.append((objparam[match][6], objparam[match][7], objparam[match][8]))
        objparamPrev = objparam



src = np.array([
    [10, 10, 10],
    [10, 10, 20],
    [10, 20, 10],
    [10, 20, 20],
])

dst = np.array([
    [10, 10, 20],
    [10, 10, 30],
    [10, 20, 20],
    [10, 20, 30],
])
print(dst)

retval, out, inliners = cv2.estimateAffine3D(src, dst, ransacThreshold = 0.1)

#print(names1)
#print(retval,'\nA matrice:\n', out,'\ninliners:', inliners)

#kiszámolni a közös pontokat [u, v] koordináta-> u1, v1, u2, v2
#depth képből kiszámolni az [x,y,z] koordinátát az adott pontokhoz -> [ui, vi] ->[xi, yi, zi]
#cv2.estimateAffine3D(src, dst[, out[, inliers[, ransacThreshold[, confidence]]]]) → retval, out, inliers ->legjobb A közelítés
'''




######################## IT ALL STARTED HERE ###################################

outPrev = np.eye(4)
imgprevu = []
map_u, map_v = cv2.initUndistortRectifyMap(camera_matrix, distortion_coefficients, None, camera_matrix, (image_width,image_height), cv2.CV_32FC1)
poses = []




#read images
'''
imgprev = cv2.imread('HW/g1/rgb/1.jpg')
imgprevdpt = cv2.imread('HW/g1/depth/1.png', -1)
imgprev = cv2.cvtColor(imgprev, cv2.COLOR_BGR2GRAY)
imgprevu = cv2.undistort(imgprev, camera_matrix, distortion_coefficients, None, camera_matrix)
imgprevdptu = cv2.undistort(imgprevdpt, camera_matrix, distortion_coefficients, None, camera_matrix)'''

for item, data in myAnswers.items():
  imgpath_rgb = item
  print(imgpath_rgb)
  item = item[:-3]
  first,second = item.split("rgb")
  imgpath_dpt = first + 'depth' + second + 'png'

  img = cv2.imread(imgpath_rgb)
  imgdpt = cv2.imread(imgpath_dpt, -1)

  #getting gray images

  img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

  #undistorting img

  imgu = cv2.undistort(img, camera_matrix, distortion_coefficients, None, camera_matrix)
  imgdptu = cv2.undistort(imgdpt, camera_matrix, distortion_coefficients, None, camera_matrix)

  #első elem vizsgálata:
  if imgprevu == []:

    out = np.eye(4)
    poses.append(out)

    outPrev = out
    imgprevu = imgu
    imgprevdptu = imgdptu
    print(out)

  else:
    #keypoint matching
    orb = cv2.ORB_create()
    kpprev, desprev = orb.detectAndCompute(imgprevu, None)
    kp, des = orb.detectAndCompute(imgu, None)
    bf = cv2.BFMatcher(cv2.NORM_HAMMING)
    matches = bf.knnMatch(desprev, des, k = 2)


    list_kpprev = []
    list_kp = []

    #getting the good match coordinates
    good = []
    for m, n in matches:
      if m.distance < 0.55*n.distance:
        good.append([m])

        imgprev_idx = m.queryIdx
        img_idx = m.trainIdx
        
        (x1, y1) = kpprev[imgprev_idx].pt
        (x2, y2) = kp[img_idx].pt
        list_kpprev.append((x1, y1))
        list_kp.append((x2, y2))

    array_kpprev = np.uint16(list_kpprev).reshape(-1,1,2)
    array_kp = np.uint16(list_kp).reshape(-1,1,2)


  #checking if it is a new series of frame
    if len(list_kp) < 10:
      print('new frameset :', len(list_kp))

      out = np.eye(4)
      print(out)
      poses.append(out)
      outPrev = out
      imgprevu = imgu
      imgprevdptu = imgdptu


    else:
      print('matches :', len(list_kp))
      matpointsprev = []
      matpoints = []

      #getting xyz coordinates for the prev image
      for i in list_kpprev:

          u = int(i[0])
          v = int(i[1])
          
          u_new = map_u[v,u]
          v_new = map_v[v,u]

          #solution where depth = z
          z = imgprevdptu[int(v_new),int(u_new)]
          z = z/1000
          #print(z)
          x = (z*u_new-z*px)/fx
          y = (z*v_new-z*py)/fy
          y = -y
          matpointsprev.append([x,y,z])
          print

      #getting xyz coordinates for the actual image
      for i in list_kp:

          u = int(i[0])
          v = int(i[1])
          
          u_new = map_u[v,u]
          v_new = map_v[v,u]
          

          #solution where depth = z
          z = imgdptu[int(v_new),int(u_new)]
          z = z/1000
          
          x = (z*u_new-z*px)/fx
          y = (z*v_new-z*py)/fy
          y = -y
          matpoints.append([x,y,z])

      matpointsprev = np.array(matpointsprev).reshape(-1,3) 
      matpoints = np.array(matpoints).reshape(-1,3)   
      #print(matpoints)
      #print(matpointsprev)

      #getting affine matrix

      retval, out, liners = cv2.estimateAffine3D(matpointsprev, matpoints, ransacThreshold=0.01) 

      #add 4. row
      newrow = [0,0,0,1]
      out = np.vstack([out, newrow])
      out = np.linalg.inv(out)
      #out = np.matmul(out, outPrev)
      poses.append(out)
      print(out)

      #giving the parameters for the next iteration
      outPrev = out
      imgprevu = imgu
      imgprevdptu = imgdptu

cntr=0
for i in myAnswers:
  myAnswers[allDestination[cntr]]['poses']=[poses[cntr][0][0], poses[cntr][0][1], poses[cntr][0][2], poses[cntr][0][3],
                                            poses[cntr][1][0], poses[cntr][1][1], poses[cntr][1][2], poses[cntr][1][3],
                                            poses[cntr][2][0], poses[cntr][2][1], poses[cntr][2][2], poses[cntr][2][3]]
  cntr+=1

HW/g1/rgb/1.jpg
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
HW/g1/rgb/33.jpg
matches : 64
[[ 1.00235174 -0.00432047  0.04134961  0.10194345]
 [ 0.00255406  0.98062993 -0.00965156 -0.01854033]
 [-0.08851469 -0.0057688   1.05798109 -0.03851982]
 [ 0.          0.          0.          1.        ]]
HW/g1/rgb/60.jpg
matches : 54
[[ 1.00364557  0.00683762  0.07658473  0.10889177]
 [ 0.03484582  1.01946267 -0.00814553  0.0160288 ]
 [-0.04170812  0.04326453  0.9498505   0.02082783]
 [ 0.          0.          0.          1.        ]]
HW/g1/rgb/89.jpg
matches : 70
[[ 0.99041557  0.0226098   0.07514501  0.09231288]
 [-0.01705396  1.01374852 -0.03513311  0.02781189]
 [-0.01378546  0.0065819   0.90137688  0.07662033]
 [ 0.          0.          0.          1.        ]]
HW/g1/rgb/123.jpg


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:133: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.


matches : 61
[[ 1.00049817 -0.00305524 -0.05772358  0.09402374]
 [-0.00539597  1.00539965  0.03196634 -0.0102559 ]
 [ 0.06775291  0.01349934  0.96635167  0.01190036]
 [ 0.          0.          0.          1.        ]]
HW/g1/rgb/145.jpg
matches : 32
[[ 0.99889807 -0.00952812  0.02022752  0.04434172]
 [-0.00991005  0.98371882 -0.03265787  0.09694245]
 [ 0.00180216  0.08723445  0.9768252  -0.02934   ]
 [ 0.          0.          0.          1.        ]]
HW/g1/rgb/159.jpg
matches : 161
[[ 9.86341357e-01 -1.55804119e-03 -1.10558780e-01  8.85849723e-03]
 [ 8.24674624e-04  1.00818219e+00  6.49477431e-03  1.57341849e-02]
 [ 1.35078600e-01 -6.66883631e-02  1.03352072e+00 -5.41161024e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
HW/g1/rgb/171.jpg
matches : 123
[[ 0.97366167 -0.0161736  -0.10286014 -0.00310699]
 [ 0.02663604  0.99558376  0.00489566 -0.00110682]
 [ 0.11969741 -0.03592643  1.02538499 -0.0358611 ]
 [ 0.          0.          0.          1.        ]]
HW/g1/rg

**HowTo**: Run all the block excluding the **Main Loop** and the ones after. **Main Loop** is for training the network. It's already done, and the best network is donwloaded from the Git project.

**Initialization**

In [0]:
# Imports ----------------------------------------------------------------------
import torch
import torch.nn as nn
import torchvision
from torchvision import transforms
from torch import optim
import numpy as np
import matplotlib.pyplot as plt
from skimage import io, transform
from PIL import Image # for Image.open()
import torch.nn.functional as F
import cv2

# Classes ------------------------------------------------------------------
classes = subclassNames[0]
classes_num = len(classes) # Number of classes to classify
#print(classes_num)

# Hyper parameters -------------------------------------------------------------
batch_size=128
numEpoch = 100
patience = 10 # Patience parameter for Early Stopping: if the best accuracy is not updated in "patience" steps, Main Loop is stopped (avoiding overfitting)
learning_rate = 1e-1

# Utilizing the GPU
haveCuda = torch.cuda.is_available()

**Convolutional Module + Network Def**

In [0]:
# Convolutional module (Conv+ReLU+BatchNorm) -----------------------------------
class Conv(nn.Module):
    def __init__(self, in_channels, channels, stride=1):
        super(Conv, self).__init__()

        self.conv = nn.Conv2d(in_channels, channels, kernel_size=3, stride=stride, padding=1, bias=False)        
        self.bn = nn.BatchNorm2d(channels)
        
    def forward(self,x):
        return self.bn(torch.relu(self.conv(x)))

class ConvNet(nn.Module):
    def __init__(self, base_channels=16, in_channels=3, num_classes=classes_num):
        super(ConvNet, self).__init__()
        
        self.c11 = Conv(in_channels, base_channels)
        self.c12 = Conv(base_channels, base_channels)   
        self.d1 = Conv(base_channels, base_channels*2, 2) # Downscale using strided convolution and expand channels
        
        self.c21 = Conv(base_channels*2, base_channels*2)
        self.c22 = Conv(base_channels*2, base_channels*2)     
        self.d2 = Conv(base_channels*2, base_channels*4, 2)
        
        self.c31 = Conv(base_channels*4, base_channels*4)
        self.c32 = Conv(base_channels*4, base_channels*4)       
        self.d3 = Conv(base_channels*4, base_channels*8, 2)
        
        self.c41 = Conv(base_channels*8, base_channels*8)
        self.c42 = Conv(base_channels*8, base_channels*8)       
        self.d4 = Conv(base_channels*8, base_channels*16, 2)
        
        self.c51 = Conv(base_channels*16, base_channels*16)
        self.c52 = Conv(base_channels*16, base_channels*16)           
        self.d5 = Conv(base_channels*16, base_channels*32, 2) # Input image is 32x32 -> after 5 downscaling the activation map is 1x1
        
        # Classifier is a normal 1x1 convolution that produces num_classes class scores
        # This layer does not have BatchNorm of ReLU
        self.classifier = nn.Conv2d(base_channels*32,num_classes,kernel_size=1)
        
    def forward(self,x):
        x = self.d1(self.c12(self.c11(x)))
        x = self.d2(self.c22(self.c21(x)))
        x = self.d3(self.c32(self.c31(x)))
        x = self.d4(self.c42(self.c41(x)))
        x = self.d5(self.c52(self.c51(x)))
        
        # Squeeze removes dimensions that have only 1 element
        # Output of the conv layer is (batch_size x num_classes x 1 x 1)
        # After squeeze is becomes (batch_size x num_classes)
        return torch.squeeze(self.classifier(x))

**Transformation + Data Augmentation + Data Loading**

In [0]:
# Transformations + Data Augmentation for the training data -------------------- 
transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.49139968, 0.48215827, 0.44653124), (0.24703233, 0.24348505, 0.26158768))
])

transform_train = transforms.Compose([
    # Transformations regarding the image position (crop, flip, affin transform)
    transforms.RandomCrop(32,padding=4), # Random 32x32 crops (with 4-wide zero padding - this is needed because the input is 32x32 so we can't crop a 32x32 region out of it without padding)
    transforms.RandomRotation(degrees=20),
    #transforms.RandomAffine(degrees=10, shear=50),
    #transforms.RandomHorizontalFlip(p=0.5),
    # Transformations regarding the image data
    transforms.ColorJitter(brightness=0.8,contrast=0.3,saturation=0.3,hue=0.2),
    transforms.RandomGrayscale(p=0.1),
    # The following 2 transformations are a must
    transforms.ToTensor(),
    transforms.Normalize((0.49139968, 0.48215827, 0.44653124), (0.24703233, 0.24348505, 0.26158768))
])

# Data loading -----------------------------------------------------------------
data_path_train = 'trafficSignsHW/trainFULL'
data_path_test = 'trafficSignsHW/testFULL'

train_dataset = torchvision.datasets.ImageFolder(root=data_path_train, transform=transform_train)
test_dataset = torchvision.datasets.ImageFolder(root=data_path_test, transform=transform_test)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

**Function for creating things + Display**



In [0]:
# Instantiate network + convert it to CUDA -------------------------------------
def createNet():
    net = ConvNet()
    if haveCuda:
        net = net.cuda()
    return net

# Fucntion for creating the Loss Function --------------------------------------
def createLoss():
    return nn.CrossEntropyLoss()

# Function for creating the Optimizer ------------------------------------------
def createOptimizer():
    return optim.SGD(net.parameters(), lr=learning_rate, momentum=0.9, nesterov=True, weight_decay=1e-4)

# Cosine annealing learning rate scheduler - in 50 epochs the lr will become 0.01
def createScheduler():
    return optim.lr_scheduler.CosineAnnealingLR(optimizer,numEpoch,eta_min=1e-2)

# Display ----------------------------------------------------------------------
from IPython.display import HTML, display

def progress(value, max=100):
    return HTML("""
        <progress
            value='{value}'
            max='{max}',
            style='width: 100%'
        >
            {value}
        </progress>
    """.format(value=value, max=max))

**Train Function (1 epoch)**

In [0]:
# Function for training a single epoch -----------------------------------------
def train(epoch):
    # variables for loss
    running_loss = 0.0
    correct = 0.0
    total = 0
   
    net.train() # set the network to train (for batchnorm and dropout)

    bar = display(progress(0, len(train_loader)), display_id=True) # Create progress bar

    for i, (images, labels) in enumerate(train_loader, 0): # inputs == one minibatch of images, inputs == corresponding labels
        # Convert to cuda
        if haveCuda:
            images, labels = images.cuda(), labels.cuda()

        optimizer.zero_grad() # Clear any previous gradients (otherwise it would accumulate)

        outputs = net(images) # Forward: Calculating the Network's Output for every image in a batch (e.g. for 128 images there will be a 128 x classes_num tensor, each row representing an image and each column is the "goodnes value" of the class in the given index) 
        loss = criterion(outputs, labels) # Loss    
        loss.backward() # Backpropagation      
        optimizer.step() # Gradient method

        # Do not include these steps in the computational graph (otherwise gradient would be calculated)
        with torch.no_grad():
            # Accumulate loss
            running_loss += loss.item()        
            _, predicted = torch.max(outputs, 1) # Get indices of the largest goodness values: For every image we will get a number, the index of the class for which the "goodness value" was the greatest
            correct += predicted.eq(labels).sum().item() # Count how many of the predictions equal the labels
            total += labels.size(0) # Accumulate number of total images seen 

        """
        if (i % 100 == 0):
              print(f'labels: {labels}')
              print(f'output: {outputs}')
              print(f'predicted: {predicted}, correct: {correct}, total: {total}')
        """
      
        bar.update(progress(i+1, len(train_loader))) 

    # Return loss and accuracy
    tr_loss = running_loss / i
    tr_corr = correct / total * 100
    print("Train epoch %d loss: %.3f correct: %.2f" % (epoch + 1, running_loss / i, tr_corr))
    return tr_loss,tr_corr

**Validation Function (1 epoch)**

In [0]:
# Function for validating a single epoch ---------------------------------------
def val(epoch):
    # variables for loss
    running_loss = 0.0
    correct = 0.0
    total = 0
   
    net.eval() # set the network to eval  (for batchnorm and dropout)

    bar = display(progress(0, len(test_loader)), display_id=True) # Create progress bar

    for i, (images, labels) in enumerate(test_loader, 0):
        # Convert to cuda
        if haveCuda:
            images, labels = images.cuda(), labels.cuda()

        # Do not include these steps in the computational graph (otherwise gradient would be calculated)
        with torch.no_grad():         
            outputs = net(images) # Forward
            loss = criterion(outputs, labels) # Loss

            # Compute statistics, just like before
            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            correct += predicted.eq(labels).sum().item()
            total += labels.size(0)

            

        bar.update(progress(i+1, len(test_loader))) # Progress bar update

    # Return loss and accuracy
    val_loss = running_loss / i
    val_corr = correct / total * 100
    print("Test epoch %d loss: %.3f correct: %.2f" % (epoch + 1, running_loss / i, val_corr))
    return val_loss,val_corr

Main Loop (do not run this!)

In [22]:
"""
# Containers for losses and accuracies for every epoch -------------------------
train_accs = []
train_losses = []
val_accs = []
val_losses = []

best_acc = 0 # Best validation accuracy (this will be updated once a greater acc is found + the model will be saved)

# Set pseudo-random generator seeds to make multiple runs comparable -----------
torch.manual_seed(1)
if haveCuda:
    torch.cuda.manual_seed(1)

# Create net, criterion, optimizer and scheduler -------------------------------
net = createNet()
criterion = createLoss()
optimizer = createOptimizer()
scheduler = createScheduler()
wait = 0 # Counter variable for Early Stopping, if "wait" reaches "patience", Main Loop is stopped

# Main Loop --------------------------------------------------------------------
for epoch in range(numEpoch):
    scheduler.step() # LR scheduler
    
    # Train
    loss,acc = train(epoch) # acc == accurate
    train_accs.append(acc)
    train_losses.append(loss)
    
    # Validate
    loss,acc = val(epoch) # acc == accurate
    val_accs.append(acc)
    val_losses.append(loss)
    
    # Saving the model
    if acc > best_acc:
        print("Best Model, Saving")
        best_acc = acc
        torch.save(net.state_dict(),"model.pth")
        wait = 0
    else:
      wait += 1
      if wait == patience:
        print(f'Patience reached, Early Stopping at Epoch {epoch+1}')
        break
"""

'\n# Containers for losses and accuracies for every epoch -------------------------\ntrain_accs = []\ntrain_losses = []\nval_accs = []\nval_losses = []\n\nbest_acc = 0 # Best validation accuracy (this will be updated once a greater acc is found + the model will be saved)\n\n# Set pseudo-random generator seeds to make multiple runs comparable -----------\ntorch.manual_seed(1)\nif haveCuda:\n    torch.cuda.manual_seed(1)\n\n# Create net, criterion, optimizer and scheduler -------------------------------\nnet = createNet()\ncriterion = createLoss()\noptimizer = createOptimizer()\nscheduler = createScheduler()\nwait = 0 # Counter variable for Early Stopping, if "wait" reaches "patience", Main Loop is stopped\n\n# Main Loop --------------------------------------------------------------------\nfor epoch in range(numEpoch):\n    scheduler.step() # LR scheduler\n    \n    # Train\n    loss,acc = train(epoch) # acc == accurate\n    train_accs.append(acc)\n    train_losses.append(loss)\n    \n  

Function for classifying a single image + Loading 1 image

In [0]:
"""
imsize = 32
loader = transforms.Compose([transforms.Resize(imsize),
                             transforms.ToTensor(),
                             transforms.Normalize((0.49139968, 0.48215827, 0.44653124), (0.24703233, 0.24348505, 0.26158768))                           
                             ])

def imageLoader(path):
    #image = io.imread(path)
    image = Image.open(path)
    image = loader(image).float()
    image = image.unsqueeze(0)
    return image

def imageClassifier(net, image):
  with torch.no_grad():         
    outputs = net(image) # Forward
    print(outputs)
    print(outputs.sum())
    predicted_value, predicted_label = torch.max(outputs, -1)

  return predicted_value, predicted_label

img = imageLoader('TestFiles/Potatoes/walk_2.jpg')
a, b = imageClassifier(net, img)
print(a, b)
"""

Plotting

In [0]:
"""
%matplotlib inline

# X coordinate for plotting
x = np.arange(numEpoch)

plt.figure(figsize=(20,10))

# Train is red, validation is blue
plt.subplot(1,2,1)
plt.plot(x,train_accs,'r')
plt.plot(x,val_accs,'b')

plt.subplot(1,2,2)
plt.plot(x,train_losses,'r')
plt.plot(x,val_losses,'b')

plt.show()

# Get a minibatch from the test loader and convert to cuda
inputs, labels = next(iter(test_loader))
if haveCuda:
    inputs, labels = inputs.cuda(), labels.cuda()

# forward
outputs = net(inputs)

# Get predicted class indices
_, predicted = torch.max(outputs, 1)

# Values used for normalization
mean = torch.Tensor((0.49139968, 0.48215827, 0.44653124)).unsqueeze(1).unsqueeze(1)
std = torch.Tensor((0.24703233, 0.24348505, 0.26158768)).unsqueeze(1).unsqueeze(1)

# List of subplots - we'll use 16 images
f, axarr = plt.subplots(2, 8,figsize=(20, 5))

# For every image-prediction pair
for i,(img,pred) in enumerate(zip(inputs,predicted)):
    # undo the normalization
    img_rescaled = img.cpu() * std + mean
    
    # Get predicted class name
    name = classes[pred.cpu().item()]
    
    # Permutation needed because in PyTorch the channel dimension comes first,
    # but in numpy and opencv it comes last (3x32x32) -> (32x32x3)
    axarr[i//8,i%8].imshow(img_rescaled.permute(1,2,0))
    
    # Set title to class name
    axarr[i//8,i%8].set_title(name)
    
    # Hide grid lines
    axarr[i//8,i%8].grid(False)
    
    # Hide axes ticks
    axarr[i//8,i%8].set_xticks([])
    axarr[i//8,i%8].set_yticks([])
    
    # Only do the first 16
    if i == 15:
        break

Classification Test

In [0]:
"""
#Loading an image
from skimage import io, transform

image = io.imread('trafficSignsHW/testFULL/Bump/img(8200).jpg')

# Loading the previously saved model
my_net = createNet()
loaded_state_dict = torch.load('model.pth')
my_net.load_state_dict(loaded_state_dict)

value, label = ImageClassify(my_net, image)

Single Image Transform Test

In [0]:
"""
imsize = 32
loader = transforms.Compose([transforms.Resize(imsize),
                             transforms.ToTensor(),
                             transforms.Normalize((0.49139968, 0.48215827, 0.44653124), (0.24703233, 0.24348505, 0.26158768))                           
                             ])

def image_loader(path):
    image = Image.open(path)
    image = loader(image).float()
    image = image.unsqueeze(0)
    return image

path = 'trafficSignsHW/testFULL/Bump/img(8200).jpg'
image = image_loader(path)

outputs = net(image)
adss, predicted = torch.max(outputs, -1)
print(adss, predicted)

# **Deep Learning**

#Teszt-Balage

This part estimates the correct class for the images given by Andris in Task 1.

In [0]:
# Loading the best Net ---------------------------------------------------------
loaded_state_dict = torch.load('model_Final.pth')
net_loaded = createNet()
net_loaded.load_state_dict(loaded_state_dict)

# Single Image Transform -------------------------------------------------------
imsize = 32
loader = transforms.Compose([torchvision.transforms.ToPILImage(),
                             transforms.Resize(imsize),
                             transforms.CenterCrop(32),
                             transforms.ToTensor(),                        
                             ])

# Single Image Classifier ------------------------------------------------------
def imageClassifier(net, image):
  with torch.no_grad():
    net.eval()       
    outputs = net(image) # Forward
    predicted_value, predicted_label = torch.max(outputs, -1)

  return predicted_value, predicted_label

# Work -------------------------------------------------------------------------
"""
cntr=0
for i in imgsRgb:
  plt.subplot(24,3,cntr+1)
  plt.imshow(drawBBs(myAnswers[allDestination[cntr]]["objects"], i))
  cntr+=1
  if(cntr==20):
    break
"""
cntr=0
cntr1=0

# Loops over all the images
for i in imgsRgb: 
  objectX=myAnswers[allDestination[cntr]]["objects"]

  cntr2=0
  for j in objectX:
    if(j[4]==0):

      imgCpy=np.copy(i)
      #plt.imshow(imgCpy)

      Cropped=imgCpy[max((j[1]-j[3]//2),0):(j[1]+j[3]//2),max((j[0]-j[2]//2),0):(j[0]+j[2]//2)]

      #cv2.imwrite('AndrisImages/'+str(cntr)+'.jpg', Cropped)   
      #plt.subplot(5,3,cntr1+1)
      #plt.imshow(Cropped)

      cntr1+=1

      Cropped = loader(Cropped).float()
      Cropped = Cropped.unsqueeze(0)
      Cropped = Cropped.cuda()

      a, b = imageClassifier(net_loaded, Cropped) # a: predicted value, b: predicted class
      correct_class = b

      myAnswers[allDestination[cntr]]["objects"][cntr2][5]=correct_class

    cntr2+=1
  cntr+=1
"""
  if(cntr==20):
    break
"""

Mounting Drive

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Visualizing EVERYTING!!

In [0]:
%matplotlib inline
plt.figure(figsize=(30,300))

cntr=0
for i in imgsRgb:
  if(cntr<20):
    cntr+=1
    continue
  plt.subplot(24,2,cntr+1)
  plt.imshow(drawBBs(myAnswers[allDestination[cntr]]["objects"], i))
  cntr+=1
  if(cntr==40):
    break

# Evaluation

This snippet assumes that the contents of the downloaded zip file are in the HW folder, and that your predictions are in a dictionary called predictions that adheres to the format specified above

In [0]:
from HW.evaluate import evaluate
file = open('HW/annotations.pickle','rb')
predictions = pickle.load(file)
predictions=myAnswers
evaluate(predictions)
